CREATE TABLE IF NOT EXISTS DZIALANIA (
    id_dzl INTEGER PRIMARY KEY,
    id_program INTEGER NOT NULL,
    id_os INTEGER NOT NULL,
    nazwa TEXT NOT NULL,
    FOREIGN KEY (id_program) REFERENCES PROGRAMY(id_program) ON DELETE CASCADE,
    FOREIGN KEY (id_os) REFERENCES OSIE(id_os) ON DELETE CASCADE
);