CREATE TABLE IF NOT EXISTS FTD_ELEMENTY (
    id_ftd_element INTEGER PRIMARY KEY,
    id_ftd INTEGER NOT NULL,
    id_dzialanie INTEGER NOT NULL,
    FOREIGN KEY (id_ftd) REFERENCES FTD(id_ftd) ON DELETE SET NULL
);