CREATE TABLE IF NOT EXISTS OSIE (
    id_os INTEGER PRIMARY KEY,
    id_program INTEGER NOT NULL,
    nazwa TEXT NOT NULL,
    FOREIGN KEY (id_program) REFERENCES PROGRAMY(id_program) ON DELETE CASCADE
);